package chatexport

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"html"
	"io"
	"strings"
	"time"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

// RenderHTML writes doc as a single self-contained HTML file: charts are
// embedded as base64 PNG data URIs (the same PNGs RenderPDF uses, built
// once by BuildDoc/BuildCompiledDoc) and all CSS is inlined, so the file
// has zero external dependencies and opens correctly straight off disk.
// Each conversation gets its own <section class="conversation">, with a
// two-level TOC (conversation, then indented turn links) when there's more
// than one. Typography, color palette, and the masthead/footer mirror
// RenderPDF (see exportStyles/drawRunningHeader in pdf.go) so a reader sees
// the same document whichever format they open.
//
// Message text is converted per-turn through goldmark's *default* HTML
// renderer (extension.GFM, no html.WithUnsafe), so any HTML-looking text
// an assistant reply happens to contain is escaped rather than executed -
// an export leaves the app's trust boundary, so raw HTML from LLM output
// must never run in the reader's browser.
func RenderHTML(doc *CompiledDoc, w io.Writer) error {
	md := goldmark.New(goldmark.WithExtensions(extension.GFM))

	var toc strings.Builder
	var body strings.Builder

	fmt.Fprintf(&body, "<div class=\"masthead\"><img class=\"masthead-icon\" src=\"data:image/png;base64,%s\" alt=\"\"><span class=\"masthead-word\">LiveReview</span></div>\n",
		base64.StdEncoding.EncodeToString(logoIconPNG))
	fmt.Fprintf(&body, "<h1 id=\"top\">%s</h1>\n", html.EscapeString(doc.Title))
	if doc.Subtitle != "" {
		fmt.Fprintf(&body, "<p class=\"subtitle\">%s</p>\n", html.EscapeString(doc.Subtitle))
	}
	fmt.Fprintf(&body, "<p class=\"meta\">Generated %s &middot; %d conversation(s)</p>\n",
		time.Now().Format("2006-01-02 15:04"), len(doc.Conversations))
	body.WriteString("<hr class=\"divider\">\n")

	multi := len(doc.Conversations) > 1
	for ci, conv := range doc.Conversations {
		convAnchor := fmt.Sprintf("conversation-%d", ci+1)
		convHeading := conv.Conversation.Title
		if multi {
			convHeading = fmt.Sprintf("Conversation %d — %s", ci+1, conv.Conversation.Title)
		}
		fmt.Fprintf(&toc, "<a href=\"#%s\" class=\"toc-conversation\">%s</a>\n", convAnchor, html.EscapeString(convHeading))

		fmt.Fprintf(&body, "<section id=\"%s\" class=\"conversation\">\n<h2>%s</h2>\n", convAnchor, html.EscapeString(convHeading))
		fmt.Fprintf(&body, "<p class=\"meta\">%d turns &middot; updated %s</p>\n",
			len(conv.Turns), conv.Conversation.UpdatedAt.Format("2006-01-02 15:04"),
		)

		for _, turn := range conv.Turns {
			anchor := fmt.Sprintf("%s-turn-%d", convAnchor, turn.Seq)
			navLabel := fmt.Sprintf("Turn %d &middot; %s", turn.Seq, roleLabel(turn.Role))
			fmt.Fprintf(&toc, "<a href=\"#%s\" class=\"toc-turn\">%s</a>\n", anchor, navLabel)

			if err := renderTurnHTML(&body, md, anchor, turn); err != nil {
				return fmt.Errorf("conversation %d: %w", ci+1, err)
			}
		}

		body.WriteString("</section>\n")
	}

	body.WriteString("<footer class=\"doc-footer\">Generated by LiveReview</footer>\n")

	page := fmt.Sprintf(htmlPageTemplate, html.EscapeString(doc.Title), exportCSS, toc.String(), body.String())
	_, err := w.Write([]byte(page))
	return err
}

// renderTurnHTML appends one turn's section (kicker, text, charts, files,
// debug artifacts) to body. The kicker reuses turnKicker (markdown.go) -
// role plus a time, deliberately never the word "Turn" or its sequence
// number, which repeat on every single turn - so the PDF and HTML exports
// agree on what's worth emphasizing and what isn't. User turns get their
// own card color and left accent (see exportCSS's .turn-user) so they read
// as a quote at a glance, the same way RenderPDF's Blockquote style does.
func renderTurnHTML(body *strings.Builder, md goldmark.Markdown, anchor string, turn ExportTurn) error {
	fmt.Fprintf(body, "<section id=\"%s\" class=\"turn turn-%s\">\n<p class=\"kicker\">%s</p>\n",
		anchor, turn.Role, html.EscapeString(turnKicker(turn)))

	if strings.TrimSpace(turn.Text) != "" {
		var buf bytes.Buffer
		if err := md.Convert([]byte(normalizeSoftWraps(turn.Text)), &buf); err != nil {
			return fmt.Errorf("render turn text: %w", err)
		}
		body.Write(buf.Bytes())
	}

	for _, chart := range turn.Charts {
		body.WriteString("<figure class=\"chart\">\n")
		fmt.Fprintf(body, "<img src=\"data:image/png;base64,%s\" alt=\"%s\">\n",
			base64.StdEncoding.EncodeToString(chart.PNG), html.EscapeString(chart.Title))
		if chart.Title != "" || chart.Description != "" {
			fmt.Fprintf(body, "<figcaption><strong>%s</strong> %s</figcaption>\n",
				html.EscapeString(chart.Title), html.EscapeString(chart.Description))
		}
		if len(chart.Stats) > 0 {
			body.WriteString("<ul class=\"stat-list\">\n")
			for _, stat := range chart.Stats {
				fmt.Fprintf(body, "<li><strong>%s:</strong> %s</li>\n",
					html.EscapeString(stat.Label), html.EscapeString(stat.Value))
			}
			body.WriteString("</ul>\n")
		}
		body.WriteString("</figure>\n")
	}

	if len(turn.Files) > 0 {
		body.WriteString("<table class=\"files\"><thead><tr><th>File</th><th>Kind</th><th>Rows</th></tr></thead><tbody>\n")
		for _, f := range turn.Files {
			fmt.Fprintf(body, "<tr><td>%s</td><td>%s</td><td>%d</td></tr>\n",
				html.EscapeString(f.Filename), html.EscapeString(f.Kind), f.Rows)
		}
		body.WriteString("</tbody></table>\n")
	}

	if len(turn.DebugArtifacts) > 0 {
		fmt.Fprintf(body, "<details class=\"debug\"><summary>Debug artifacts</summary><pre>%s</pre></details>\n",
			html.EscapeString(string(prettyJSON(turn.DebugArtifacts))))
	}

	body.WriteString("</section>\n")
	return nil
}

const htmlPageTemplate = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s</title>
<style>%s</style>
</head>
<body>
<nav class="toc"><a href="#top" class="toc-title">Contents</a>
%s</nav>
<main>
%s</main>
</body>
</html>
`

// exportCSS's palette mirrors the PDF's exportStyles/col* variables (pdf.go)
// so the two formats read as the same document: --brand is colBrand
// (blue-600, lightened to blue-400 in dark mode for contrast), --fg/--muted
// track colNavy/colMuted, and --border/--table-bg track colBorder/colTableBg.
const exportCSS = `
:root{color-scheme:light dark;--bg:#fff;--fg:#0f172a;--muted:#64748b;--border:#e2e8f0;--table-bg:#f8fafc;--brand:#2563eb;--user-bg:#eff6ff;--assistant-bg:#f8fafc;}
@media (prefers-color-scheme:dark){:root{--bg:#0f1115;--fg:#e6e9ef;--muted:#94a3b8;--border:#262b33;--table-bg:#181c22;--brand:#60a5fa;--user-bg:#152136;--assistant-bg:#171a1f;}}
*{box-sizing:border-box;}
body{margin:0;background:var(--bg);color:var(--fg);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;display:flex;min-height:100vh;line-height:1.55;}
nav.toc{width:230px;flex-shrink:0;padding:24px 16px;border-right:1px solid var(--border);position:sticky;top:0;align-self:flex-start;height:100vh;overflow-y:auto;}
nav.toc a{display:block;padding:5px 8px;border-radius:6px;color:var(--fg);text-decoration:none;font-size:13.5px;}
nav.toc a.toc-title{font-weight:700;margin-bottom:8px;color:var(--muted);text-transform:uppercase;font-size:11px;letter-spacing:.05em;}
nav.toc a.toc-conversation{font-weight:600;margin-top:10px;}
nav.toc a.toc-turn{padding-left:16px;color:var(--muted);font-size:12.5px;}
nav.toc a:hover{background:var(--border);}
main{flex:1;min-width:0;max-width:800px;padding:40px 44px 60px;}
.masthead{display:flex;align-items:center;gap:8px;margin-bottom:32px;}
.masthead-icon{width:22px;height:22px;display:block;}
.masthead-word{font-weight:700;font-size:14.5px;color:var(--brand);letter-spacing:.01em;}
h1{font-size:34px;font-weight:700;color:var(--brand);margin:0 0 8px;letter-spacing:-.01em;line-height:1.2;}
p.subtitle{font-size:16.5px;color:var(--muted);margin:0 0 14px;font-weight:400;}
p.meta{color:var(--muted);font-size:12.5px;margin:0;}
hr.divider{border:none;border-top:1px solid var(--border);margin:22px 0 36px;}
section.conversation{margin-bottom:8px;}
section.conversation>h2{font-size:21px;font-weight:700;margin:0 0 6px;color:var(--fg);}
section.conversation>p.meta{margin-bottom:26px;}
section.turn{border:1px solid var(--border);border-left:3px solid var(--border);border-radius:10px;padding:18px 22px;margin-bottom:16px;background:var(--assistant-bg);}
section.turn-user{background:var(--user-bg);border-left-color:var(--brand);}
p.kicker{font-size:11px;margin:0 0 10px;color:var(--muted);letter-spacing:.03em;font-weight:600;}
section.turn img{max-width:100%;height:auto;border-radius:4px;display:block;}
section.turn p:last-child,section.turn ul:last-child,section.turn ol:last-child{margin-bottom:0;}
figure.chart{margin:16px 0;background:#fff;padding:14px;border-radius:8px;border:1px solid var(--border);}
/* figure.chart's background is a fixed #fff regardless of light/dark mode
   (matching the embedded PNG's own white background - see build.go/analytics.go's
   comment on why the chart spec forces a white background). Text inside it
   must therefore use fixed colors too, not the theme-adaptive --fg/--muted
   vars: in dark mode those resolve to near-white, which is nearly invisible
   against this always-white card. */
figcaption{font-size:13px;color:#64748b;margin-top:6px;}
ul.stat-list{margin:10px 0 0;padding-left:20px;font-size:13px;color:#1f2937;}
ul.stat-list li:last-child{margin-bottom:0;}
table.files{width:100%;border-collapse:collapse;margin:12px 0;font-size:13.5px;}
table.files th,table.files td{border:1px solid var(--border);padding:6px 10px;text-align:left;}
table.files th{background:var(--table-bg);color:var(--muted);font-weight:600;}
details.debug{margin-top:12px;font-size:12px;}
details.debug summary{cursor:pointer;color:var(--muted);font-weight:600;}
details.debug pre{white-space:pre-wrap;word-break:break-word;background:var(--table-bg);border:1px solid var(--border);padding:12px;border-radius:6px;overflow-x:auto;margin-top:8px;}
section.turn table:not(.files){border-collapse:collapse;width:100%;font-size:14px;}
section.turn table:not(.files) th,section.turn table:not(.files) td{border:1px solid var(--border);padding:6px 10px;}
section.turn table:not(.files) th{background:var(--table-bg);color:var(--muted);}
footer.doc-footer{margin-top:40px;padding-top:16px;border-top:1px solid var(--border);color:var(--muted);font-size:12px;}
@media (max-width:720px){body{flex-direction:column;}nav.toc{width:100%;height:auto;position:relative;border-right:none;border-bottom:1px solid var(--border);}main{padding:28px 20px;}}
`
