// Package livisql validates the SQL that Livi's LLM generates for analytics
// questions.
//
// There is no structural rewrite here anymore (no per-table shadow CTEs, no
// bound org id parameter). The guard only checks the query's *shape*:
//
//   - read-only (a single SELECT, no locking clause, no SELECT INTO, no
//     bind placeholders, no multi-statement stacking)
//   - every referenced table is on the allowed [Catalog] (a plain denylist -
//     see catalog.go's deniedTables)
//   - every referenced function is on the allowlist
//   - no `*`/`table.*` in the select list (a named-column check cannot see
//     through a star, so a secret column could otherwise ride along
//     unnamed)
//   - no reference to a column on the secretColumns denylist, by name,
//     anywhere in the query
//   - at least one `org_id = ...` comparison appears somewhere in the query,
//     and every `org_id = <literal>` comparison found anywhere in the query
//     must use the caller's actual org id - a wrong literal is rejected
//     (`org_id` compared against another column, e.g. a join condition like
//     `l.org_id = r.org_id`, is not literal-checked, since there is no fixed
//     value to check it against - see checkAExpr)
//   - no constant-vs-constant comparison (`1=1`, `'a'='a'`) or bare boolean
//     literal used as a predicate, appearing anywhere a boolean expression
//     is evaluated - the `OR 1=1` family of tautologies
//
// This is still weaker than proving the query is org-scoped: checking that a
// generated query "filters by org_id" is not soundly decidable from a parse
// tree in general (a predicate parked in a LEFT JOIN ... ON clause that
// doesn't actually filter, a correlated subquery, a CASE WHEN, org_id
// wrapped in a cast or compared via BETWEEN/IN instead of `=`, all defeat
// this walker). The literal-value and tautology checks above close the most
// common, mechanically-generated bypasses; they do not close all of them.
// This tradeoff - shape-checking instead of structural enforcement - is an
// explicit, accepted decision, not an oversight.
package livisql

import (
	"encoding/json"
	"strconv"
	"strings"

	pgquery "github.com/wasilibs/go-pgquery"
)

// maxSQLLen bounds work before the parser is invoked at all.
const maxSQLLen = 8000

type Guard struct {
	catalog Catalog
	orgID   int64
}

// New builds a guard scoped to orgID - the caller's actual, currently
// selected organization (the one the UI's org switcher has active for this
// session). Every `org_id = <literal>` comparison the query contains is
// checked against this value.
func New(catalog Catalog, orgID int64) *Guard {
	return &Guard{catalog: catalog, orgID: orgID}
}

// Rewrite validates rawSQL and returns it in canonical form (the parser's own
// deparse of the generated statement, not its original text, so comment,
// whitespace and unicode tricks cannot make the executed statement differ
// from the validated one). Despite the name, there is no structural rewrite
// - see the package doc.
func (g *Guard) Rewrite(rawSQL string) (string, error) {
	return g.validate(rawSQL)
}

// validate runs every check and returns the canonical deparse of the statement.
func (g *Guard) validate(rawSQL string) (string, error) {
	trimmed := strings.TrimSpace(rawSQL)
	if trimmed == "" {
		return "", reject(CodeUnparseable, "Write a SELECT query.", "empty query")
	}
	if len(trimmed) > maxSQLLen {
		return "", reject(CodeTooLong, "That query is too long. Ask for a narrower slice of data.",
			"query is %d bytes, limit %d", len(trimmed), maxSQLLen)
	}

	tree, err := pgquery.Parse(trimmed)
	if err != nil {
		return "", reject(CodeUnparseable, "That is not valid PostgreSQL. Check the syntax and try again.",
			"parse failed: %v", err)
	}
	if len(tree.Stmts) != 1 {
		return "", reject(CodeMultiStatement, "Send exactly one SELECT statement.",
			"expected 1 statement, got %d", len(tree.Stmts))
	}
	if tree.Stmts[0].Stmt.GetSelectStmt() == nil {
		return "", reject(CodeNotSelect, "Only SELECT queries are allowed. You cannot modify data.",
			"top-level statement is not a SELECT")
	}

	// The typed AST answers statement-shape questions; the JSON form is used for
	// the deep walk because every node is a uniform single-key object, which
	// makes the traversal total — no node type can be silently skipped because
	// we forgot to handle its Go struct.
	raw, err := pgquery.ParseToJSON(trimmed)
	if err != nil {
		return "", reject(CodeUnparseable, "That is not valid PostgreSQL. Check the syntax and try again.",
			"parse to json failed: %v", err)
	}
	var doc any
	if err := json.Unmarshal([]byte(raw), &doc); err != nil {
		return "", reject(CodeUnparseable, "That is not valid PostgreSQL. Check the syntax and try again.",
			"json decode failed: %v", err)
	}

	// Two passes: CTE names must all be known before any relation reference is
	// judged, because JSON object key order is not traversal order and a CTE can
	// otherwise be visited after the reference that resolves against it.
	w := &walker{catalog: g.catalog, orgID: g.orgID, cteNames: map[string]bool{}}
	w.collectCTEs(doc)
	w.walk(doc)
	if w.err != nil {
		return "", w.err
	}
	if !w.sawOrgFilter {
		return "", reject(CodeMissingOrgFilter,
			"Every query must filter by org_id, for example `WHERE org_id = <the organization's id>`.",
			"query has no org_id comparison anywhere")
	}

	deparsed, err := pgquery.Deparse(tree)
	if err != nil {
		return "", reject(CodeDeparse, "I could not build that query. Try a simpler shape.",
			"deparse failed: %v", err)
	}
	return deparsed, nil
}

type walker struct {
	catalog      Catalog
	orgID        int64
	cteNames     map[string]bool
	sawOrgFilter bool
	err          *RejectionError
}

func (w *walker) fail(e *RejectionError) {
	if w.err == nil {
		w.err = e
	}
}

func (w *walker) walk(node any) {
	if w.err != nil {
		return
	}
	switch v := node.(type) {
	case map[string]any:
		for key, child := range v {
			switch key {
			case "RangeVar":
				w.checkRangeVar(child)
			case "FuncCall":
				w.checkFuncCall(child)
			case "ColumnRef":
				w.checkColumnRef(child)
			case "A_Expr":
				w.checkAExpr(child)
			case "BoolExpr":
				w.checkBoolExpr(child)
			case "ParamRef":
				// Bind placeholders have no meaning here - nothing binds them
				// to anything - so a query carrying one is malformed input.
				w.fail(reject(CodePlaceholder, "Do not use bind parameters such as $1. Write literal values.",
					"query contains a parameter placeholder"))
			case "LockingClause":
				w.fail(reject(CodeLocking, "Do not use FOR UPDATE or FOR SHARE.",
					"query contains a locking clause"))
			case "intoClause":
				if child != nil {
					w.fail(reject(CodeSelectInto, "Do not use SELECT INTO.", "query contains an INTO clause"))
				}
			// Node types are capitalized in pg_query's JSON (RangeVar, FuncCall)
			// but struct fields are camelCase, so the CTE list arrives as
			// "withClause", not "WithClause".
			case "withClause":
				if m, ok := child.(map[string]any); ok {
					if rec, _ := m["recursive"].(bool); rec {
						w.fail(reject(CodeRecursiveCTE, "Do not use WITH RECURSIVE.",
							"query contains a recursive CTE"))
					}
				}
			}
			w.walk(child)
		}
	case []any:
		for _, child := range v {
			w.walk(child)
		}
	}
}

func (w *walker) checkRangeVar(node any) {
	m, ok := node.(map[string]any)
	if !ok {
		return
	}
	relname, _ := m["relname"].(string)
	schema, _ := m["schemaname"].(string)

	if schema != "" && schema != "public" {
		w.fail(reject(CodeCrossSchema, "Write table names unqualified, for example `reviews`.",
			"cross-schema relation %q.%q", schema, relname))
		return
	}

	// A name defined as a CTE by the generated query itself is fine.
	if w.cteNames[relname] {
		return
	}
	if !w.catalog.Allows(relname) {
		w.fail(reject(CodeUnknownTable,
			"The table \""+relname+"\" is not available. You can query: "+strings.Join(w.catalog.Tables(), ", ")+".",
			"relation %q is not in the catalog", relname))
	}
}

// collectCTEs records every CTE name the generated query defines, so
// checkRangeVar can tell "this is the model's own CTE" apart from "this
// should be a catalog table." Run to completion before walk().
func (w *walker) collectCTEs(node any) {
	switch v := node.(type) {
	case map[string]any:
		for key, child := range v {
			if key == "CommonTableExpr" {
				if m, ok := child.(map[string]any); ok {
					if name, _ := m["ctename"].(string); name != "" {
						w.cteNames[name] = true
					}
				}
			}
			w.collectCTEs(child)
		}
	case []any:
		for _, child := range v {
			w.collectCTEs(child)
		}
	}
}

// checkColumnRef refuses `*`/`table.*` (a named-column check cannot see
// through a star, so a secret column could ride along unnamed) and any
// reference to a column on the secretColumns denylist, by its final
// (unqualified) name segment.
func (w *walker) checkColumnRef(node any) {
	m, ok := node.(map[string]any)
	if !ok {
		return
	}
	fields, ok := m["fields"].([]any)
	if !ok || len(fields) == 0 {
		return
	}
	var last string
	for _, f := range fields {
		fm, ok := f.(map[string]any)
		if !ok {
			continue
		}
		if _, isStar := fm["A_Star"]; isStar {
			w.fail(reject(CodeStarSelect, "List the columns you need by name instead of using *.",
				"query uses * in place of named columns"))
			return
		}
		if s, ok := fm["String"].(map[string]any); ok {
			if v, ok := s["sval"].(string); ok {
				last = v
			}
		}
	}
	if last != "" && secretColumns[last] {
		w.fail(reject(CodeSecretColumn,
			"The column \""+last+"\" is not available.",
			"query references denylisted column %q", last))
	}
}

// checkAExpr records org_id filter presence, verifies the literal value of
// any `org_id = <literal>` comparison against the caller's actual org id,
// and refuses constant-vs-constant comparisons (`1=1`, `'a'='a'`) - the
// shape of an `OR 1=1` tautology.
func (w *walker) checkAExpr(node any) {
	m, ok := node.(map[string]any)
	if !ok {
		return
	}
	lexpr, hasL := m["lexpr"]
	rexpr, hasR := m["rexpr"]
	if !hasL || !hasR {
		return
	}
	if isConst(lexpr) && isConst(rexpr) {
		w.fail(reject(CodeTautology, "Do not write comparisons between two literal values.",
			"constant-vs-constant comparison in query"))
		return
	}

	otherSide, isOrgFilter := orgIDComparisonOtherSide(lexpr, rexpr)
	if !isOrgFilter {
		return
	}
	w.sawOrgFilter = true

	// org_id compared against another column (a join condition tying two
	// org_id columns together) has no fixed value to check - nothing more to
	// do here. Only a comparison against a literal can be checked.
	if !isConst(otherSide) {
		return
	}
	opName, _ := aExprOpName(m)
	if opName != "=" {
		return
	}
	val, ok := constInt64(otherSide)
	if !ok {
		return
	}
	if val != w.orgID {
		w.fail(reject(CodeWrongOrg,
			"That query filters by a different organization's id than the one you are answering for.",
			"org_id literal %d does not match the caller's org id %d", val, w.orgID))
	}
}

// aExprOpName extracts the operator string ("=", "!=", ...) from an A_Expr
// node's name field.
func aExprOpName(aExpr map[string]any) (string, bool) {
	names, ok := aExpr["name"].([]any)
	if !ok || len(names) == 0 {
		return "", false
	}
	nm, ok := names[0].(map[string]any)
	if !ok {
		return "", false
	}
	s, ok := nm["String"].(map[string]any)
	if !ok {
		return "", false
	}
	op, ok := s["sval"].(string)
	return op, ok
}

// constInt64 extracts an integer value from an A_Const node, whether it
// parsed as a numeric literal (ival) or a string literal (sval, e.g.
// `org_id = '7'`) - protojson omits a zero-valued ival's inner field
// entirely, so an empty ival object means the literal is 0.
func constInt64(node any) (int64, bool) {
	m, ok := node.(map[string]any)
	if !ok {
		return 0, false
	}
	ac, ok := m["A_Const"].(map[string]any)
	if !ok {
		return 0, false
	}
	if iv, ok := ac["ival"].(map[string]any); ok {
		n, _ := iv["ival"].(float64)
		return int64(n), true
	}
	if sv, ok := ac["sval"].(map[string]any); ok {
		if s, ok := sv["sval"].(string); ok {
			if n, err := strconv.ParseInt(s, 10, 64); err == nil {
				return n, true
			}
		}
	}
	return 0, false
}

// checkBoolExpr refuses a bare constant (`OR TRUE`, `AND FALSE`) used
// directly as a boolean operand - the other shape of a tautology injection,
// not wrapped in a comparison at all.
func (w *walker) checkBoolExpr(node any) {
	m, ok := node.(map[string]any)
	if !ok {
		return
	}
	args, ok := m["args"].([]any)
	if !ok {
		return
	}
	for _, a := range args {
		am, ok := a.(map[string]any)
		if !ok {
			continue
		}
		if _, isConstArg := am["A_Const"]; isConstArg {
			w.fail(reject(CodeTautology, "Do not use a bare TRUE/FALSE as part of a filter.",
				"bare boolean constant used as a predicate"))
			return
		}
	}
}

func isConst(node any) bool {
	m, ok := node.(map[string]any)
	if !ok {
		return false
	}
	_, ok = m["A_Const"]
	return ok
}

func isOrgIDColumnRef(node any) bool {
	m, ok := node.(map[string]any)
	if !ok {
		return false
	}
	cr, ok := m["ColumnRef"].(map[string]any)
	if !ok {
		return false
	}
	fields, ok := cr["fields"].([]any)
	if !ok || len(fields) == 0 {
		return false
	}
	last, ok := fields[len(fields)-1].(map[string]any)
	if !ok {
		return false
	}
	s, ok := last["String"].(map[string]any)
	if !ok {
		return false
	}
	name, _ := s["sval"].(string)
	return strings.EqualFold(name, "org_id")
}

// orgIDComparisonOtherSide reports whether one side of a comparison is an
// org_id column reference, and if so returns the other side (the thing
// org_id is being compared against - a literal, another column, ...).
func orgIDComparisonOtherSide(lexpr, rexpr any) (other any, isOrgFilter bool) {
	if isOrgIDColumnRef(lexpr) {
		return rexpr, true
	}
	if isOrgIDColumnRef(rexpr) {
		return lexpr, true
	}
	return nil, false
}

func (w *walker) checkFuncCall(node any) {
	m, ok := node.(map[string]any)
	if !ok {
		return
	}
	parts, ok := m["funcname"].([]any)
	if !ok || len(parts) == 0 {
		return
	}
	// A qualified function name (pg_catalog.pg_read_file) arrives as multiple
	// parts; judge the final element and reject any explicit qualification.
	names := make([]string, 0, len(parts))
	for _, p := range parts {
		pm, ok := p.(map[string]any)
		if !ok {
			continue
		}
		s, ok := pm["String"].(map[string]any)
		if !ok {
			continue
		}
		if v, ok := s["sval"].(string); ok {
			names = append(names, strings.ToLower(v))
		}
	}
	if len(names) == 0 {
		return
	}
	// SQL-standard constructs are normalized by the parser into explicitly
	// qualified calls — extract(dow FROM ts) becomes pg_catalog.extract — so
	// pg_catalog qualification has to be tolerated. It grants nothing: every
	// builtin already lives there and is always in scope, and the allowlist
	// check below still applies to the bare name, so pg_catalog.pg_read_file is
	// refused exactly like pg_read_file is.
	if len(names) == 2 && names[0] == "pg_catalog" {
		names = names[1:]
	}
	if len(names) > 1 {
		w.fail(reject(CodeUnknownFunc, "Use unqualified function names.",
			"schema-qualified function %q", strings.Join(names, ".")))
		return
	}
	if !functionAllowed(names[0]) {
		w.fail(reject(CodeUnknownFunc,
			"The function \""+names[0]+"\" is not available. Use standard aggregate, date and string functions.",
			"function %q is not in the allowlist", names[0]))
	}
}
