import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://livereview.hexmos.site/');
  await page.getByRole('textbox', { name: 'Organization Name' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).fill('Hexmos01');
  await page.getByRole('textbox', { name: 'Organization Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Admin Email' }).fill('shrijith@hexmos.com');
  await page.getByRole('textbox', { name: 'Admin Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('MegaSuperAdmin@123');
  await page.getByRole('button', { name: 'Complete Setup' }).click();
  await page.getByRole('textbox', { name: 'Paste license JWT here' }).click();
  await page.getByRole('textbox', { name: 'Paste license JWT here' }).fill('[REDACTED_GITLEAKS_15]');
  await page.getByRole('button', { name: 'Save Token' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'User Management' }).click();
  await page.getByRole('button', { name: 'Instance' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'User Management' }).click();
  await page.getByRole('link', { name: 'Add User' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('general@hexmos.com');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'First Name' }).fill('General');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Mega');
  await page.getByLabel('Role').selectOption('owner');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('MegaGeneral@123');
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('MegaGeneral@123');
  await page.getByRole('button', { name: 'Create User' }).click();
  await page.getByRole('link', { name: 'AI Providers' }).click();
  await page.getByRole('button', { name: 'Add Connector' }).click();
  await page.getByRole('button', { name: 'Google Gemini Recommended' }).click();
  await page.getByRole('textbox', { name: 'API Key' }).click();
  await page.getByRole('textbox', { name: 'API Key' }).fill('[REDACTED_GITLEAKS_14]');
  await page.getByRole('button', { name: 'Save Connector' }).click();
  await page.getByRole('link', { name: 'Git Providers' }).click();
  await page.getByRole('button', { name: 'Self-Hosted GitLab' }).click();
  await page.getByRole('textbox', { name: 'Connector Name' }).click();
  await page.getByRole('textbox', { name: 'Connector Name' }).fill('GL2130');
  await page.locator('#manual-pat').click();
  await page.locator('#manual-pat').click();
  await page.locator('#manual-pat').fill('REDACTED_GITLAB_PAT_2nm86MQp1OjJiCA.01.0y1uxj51i');
  await page.locator('#manual-pat').click();
  await page.getByRole('textbox', { name: 'Instance URL' }).click();
  await page.getByRole('textbox', { name: 'Instance URL' }).fill('https://git.apps.hexmos.com');
  await page.getByRole('button', { name: 'Add Connector' }).click();
  await page.getByRole('button', { name: 'Confirm & Save' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});