// Code generated by typed. DO NOT EDIT
package main

import (
	"fmt"
	"github.com/d1vbyz3r0/typed"
	"github.com/d1vbyz3r0/typed/handlers"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"github.com/labstack/echo/v4"
	"github.com/livereview/internal/api"
	"github.com/livereview/internal/api/auth"
	"github.com/livereview/internal/api/organizations"
	"github.com/livereview/internal/api/users"
	"github.com/livereview/internal/learnings"
	"github.com/livereview/internal/license/payment"
	"github.com/livereview/internal/provider_input/gitea"
	"github.com/livereview/internal/provider_input/github"
	"github.com/livereview/internal/provider_input/gitlab"
	"github.com/livereview/pkg/models"
	"log/slog"
	"os"
)

var UsedTypes = map[string]any{
	"api.AssignLicenseRequest":              new(api.AssignLicenseRequest),
	"api.CachedProjectData":                 new(api.CachedProjectData),
	"models.ReviewComment":                  new(models.ReviewComment),
	"*gitlab.GitLabProfile":                 new(*gitlab.GitLabProfile),
	"api.ValidateBitbucketProfileRequest":   new(api.ValidateBitbucketProfileRequest),
	"api.APIKey":                            new(api.APIKey),
	"api.ReviewEvent":                       new(api.ReviewEvent),
	"api.ReviewSummary":                     new(api.ReviewSummary),
	"api.UnifiedContextBuilderV2":           new(api.UnifiedContextBuilderV2),
	"models.InstanceDetails":                new(models.InstanceDetails),
	"api.Server":                            new(api.Server),
	"api.UnifiedCommentV2":                  new(api.UnifiedCommentV2),
	"api.AIConnectorKeyValidationRequest":   new(api.AIConnectorKeyValidationRequest),
	"api.AIConnectorKeyValidationResponse":  new(api.AIConnectorKeyValidationResponse),
	"*api.ReviewSummary":                    new(*api.ReviewSummary),
	"api.ActivityEntry":                     new(api.ActivityEntry),
	"api.DatabaseEventSink":                 new(api.DatabaseEventSink),
	"api.UnifiedBotUserInfoV2":              new(api.UnifiedBotUserInfoV2),
	"users.UserAnalytics":                   new(users.UserAnalytics),
	"auth.LoginRequest":                     new(auth.LoginRequest),
	"auth.AuthMiddleware":                   new(auth.AuthMiddleware),
	"api.AIConnectorResponse":               new(api.AIConnectorResponse),
	"[]api.AIConnectorResponse":             new([]api.AIConnectorResponse),
	"api.ActivityTracker":                   new(api.ActivityTracker),
	"api.LearningProcessorV2Impl":           new(api.LearningProcessorV2Impl),
	"*api.RepositoryAccessResponse":         new(*api.RepositoryAccessResponse),
	"api.UnifiedMRContextV2":                new(api.UnifiedMRContextV2),
	"models.CommentSeverity":                new(models.CommentSeverity),
	"models.User":                           new(models.User),
	"models.UserRole":                       new(models.UserRole),
	"api.CancelSubscriptionRequest":         new(api.CancelSubscriptionRequest),
	"api.EventData":                         new(api.EventData),
	"users.RoleUserCount":                   new(users.RoleUserCount),
	"auth.JWTClaims":                        new(auth.JWTClaims),
	"api.DeploymentConfig":                  new(api.DeploymentConfig),
	"api.LearningMetadataV2":                new(api.LearningMetadataV2),
	"api.UnifiedMergeRequestV2":             new(api.UnifiedMergeRequestV2),
	"models.ReviewResult":                   new(models.ReviewResult),
	"api.ReviewsListResponse":               new(api.ReviewsListResponse),
	"api.ActivityItem":                      new(api.ActivityItem),
	"api.LicenseStatusResponse":             new(api.LicenseStatusResponse),
	"api.ProjectWithStatus":                 new(api.ProjectWithStatus),
	"api.SeatAssignment":                    new(api.SeatAssignment),
	"users.UserOrgRole":                     new(users.UserOrgRole),
	"api.PasswordRequest":                   new(api.PasswordRequest),
	"api.ReviewAccountingResponse":          new(api.ReviewAccountingResponse),
	"api.ValidateGitLabProfileRequest":      new(api.ValidateGitLabProfileRequest),
	"api.ReviewResponse":                    new(api.ReviewResponse),
	"api.BitbucketProfile":                  new(api.BitbucketProfile),
	"api.PollingEventService":               new(api.PollingEventService),
	"api.ReviewAccountingOperationResponse": new(api.ReviewAccountingOperationResponse),
	"models.CodeDiff":                       new(models.CodeDiff),
	"models.UserWithRole":                   new(models.UserWithRole),
	"organizations.OrganizationHandlers":    new(organizations.OrganizationHandlers),
	"auth.EnsureCloudUserRequest":           new(auth.EnsureCloudUserRequest),
	"*payment.SelfHostedPurchaseResponse":   new(*payment.SelfHostedPurchaseResponse),
	"api.ReviewEventsHandler":               new(api.ReviewEventsHandler),
	"api.ReviewMetadataUpdate":              new(api.ReviewMetadataUpdate),
	"api.SubscriptionsHandler":              new(api.SubscriptionsHandler),
	"*users.UserWithRole":                   new(*users.UserWithRole),
	"auth.SetupAdminRequest":                new(auth.SetupAdminRequest),
	"api.FetchOllamaModelsRequest":          new(api.FetchOllamaModelsRequest),
	"[]api.ConnectorResponse":               new([]api.ConnectorResponse),
	"api.ValidateGitHubProfileRequest":      new(api.ValidateGitHubProfileRequest),
	"*api.BitbucketProfile":                 new(*api.BitbucketProfile),
	"*gitea.GiteaProfile":                   new(*gitea.GiteaProfile),
	"api.TestHandlers":                      new(api.TestHandlers),
	"auth.TokenPair":                        new(auth.TokenPair),
	"api.UpgradePreparePaymentRequest":      new(api.UpgradePreparePaymentRequest),
	"api.RenderPreviewResponse":             new(api.RenderPreviewResponse),
	"api.GitLabV2Provider":                  new(api.GitLabV2Provider),
	"api.OperationUsageV2":                  new(api.OperationUsageV2),
	"api.UserService":                       new(api.UserService),
	"*auth.TokenPair":                       new(*auth.TokenPair),
	"api.CreateAPIKeyRequest":               new(api.CreateAPIKeyRequest),
	"api.SeatAssignmentListResponse":        new(api.SeatAssignmentListResponse),
	"api.DiffReviewResult":                  new(api.DiffReviewResult),
	"api.QuotaStatusHandler":                new(api.QuotaStatusHandler),
	"api.SignedUpgradePreview":              new(api.SignedUpgradePreview),
	"api.UnifiedReviewCommentV2":            new(api.UnifiedReviewCommentV2),
	"api.VersionInfo":                       new(api.VersionInfo),
	"auth.RefreshRequest":                   new(auth.RefreshRequest),
	"auth.ChangePasswordRequest":            new(auth.ChangePasswordRequest),
	"auth.ContextKey":                       new(auth.ContextKey),
	"api.ListEventsCursor":                  new(api.ListEventsCursor),
	"api.QuotaStatus":                       new(api.QuotaStatus),
	"api.PlanUsageEnvelope":                 new(api.PlanUsageEnvelope),
	"users.UserProfile":                     new(users.UserProfile),
	"auth.PermissionContext":                new(auth.PermissionContext),
	"api.ReorderRequest":                    new(api.ReorderRequest),
	"*github.GitHubProfile":                 new(*github.GitHubProfile),
	"api.CompleteConnectorResponse":         new(api.CompleteConnectorResponse),
	"api.IntegrationToken":                  new(api.IntegrationToken),
	"api.TriggerReviewResponse":             new(api.TriggerReviewResponse),
	"api.WebhookOrchestratorV2":             new(api.WebhookOrchestratorV2),
	"users.CreateUserRequest":               new(users.CreateUserRequest),
	"*api.LicenseStatusResponse":            new(*api.LicenseStatusResponse),
	"api.UnifiedCommitV2":                   new(api.UnifiedCommitV2),
	"api.UnifiedTimelineItemV2":             new(api.UnifiedTimelineItemV2),
	"models.UserOrgInfo":                    new(models.UserOrgInfo),
	"*users.UserProfile":                    new(*users.UserProfile),
	"users.ChangePasswordRequest":           new(users.ChangePasswordRequest),
	"users.UserWithRole":                    new(users.UserWithRole),
	"api.PlanChangeRequest":                 new(api.PlanChangeRequest),
	"*learnings.Learning":                   new(*learnings.Learning),
	"*payment.RazorpaySubscription":         new(*payment.RazorpaySubscription),
	"api.ConnectorSetupProgress":            new(api.ConnectorSetupProgress),
	"models.OrgAnalytics":                   new(models.OrgAnalytics),
	"models.Role":                           new(models.Role),
	"users.UserService":                     new(users.UserService),
	"gitlab.GitLabTokenRequest":             new(gitlab.GitLabTokenRequest),
	"api.PasswordStatusResponse":            new(api.PasswordStatusResponse),
	"api.AIComment":                         new(api.AIComment),
	"api.DocsBuilder":                       new(api.DocsBuilder),
	"api.RepositoryAccessResponse":          new(api.RepositoryAccessResponse),
	"users.ProfileService":                  new(users.ProfileService),
	"auth.TokenService":                     new(auth.TokenService),
	"api.AIConnectorCreateRequest":          new(api.AIConnectorCreateRequest),
	"api.AutoWebhookInstaller":              new(api.AutoWebhookInstaller),
	"api.BillingActionsHandler":             new(api.BillingActionsHandler),
	"api.CatalogEntry":                      new(api.CatalogEntry),
	"api.LearningsHandler":                  new(api.LearningsHandler),
	"api.ReviewManager":                     new(api.ReviewManager),
	"users.UpdateUserRequest":               new(users.UpdateUserRequest),
	"users.UpdateProfileRequest":            new(users.UpdateProfileRequest),
	"auth.LoginResponse":                    new(auth.LoginResponse),
	"api.UnassignedUser":                    new(api.UnassignedUser),
	"api.UnifiedFileChangeV2":               new(api.UnifiedFileChangeV2),
	"api.UnifiedUserV2":                     new(api.UnifiedUserV2),
	"api.WebhookStatusSummary":              new(api.WebhookStatusSummary),
	"organizations.OrganizationService":     new(organizations.OrganizationService),
	"auth.AuthHandlers":                     new(auth.AuthHandlers),
	"api.DashboardData":                     new(api.DashboardData),
	"api.AIConnectorV2":                     new(api.AIConnectorV2),
	"api.CommentContextV2":                  new(api.CommentContextV2),
	"api.ReviewService":                     new(api.ReviewService),
	"api.UnifiedTimelineV2":                 new(api.UnifiedTimelineV2),
	"api.VariableEntry":                     new(api.VariableEntry),
	"map[string]string":                     new(map[string]string),
	"api.APIKeyManager":                     new(api.APIKeyManager),
	"api.WebhookHealthSummary":              new(api.WebhookHealthSummary),
	"api.WebhookProviderRegistry":           new(api.WebhookProviderRegistry),
	"auth.UserInfo":                         new(auth.UserInfo),
	"api.PasswordVerifyRequest":             new(api.PasswordVerifyRequest),
	"api.ConnectorDetails":                  new(api.ConnectorDetails),
	"api.DashboardManager":                  new(api.DashboardManager),
	"*users.UserAnalytics":                  new(*users.UserAnalytics),
	"users.ProfileHandlers":                 new(users.ProfileHandlers),
	"auth.Permission":                       new(auth.Permission),
	"api.DiffReviewRequest":                 new(api.DiffReviewRequest),
	"api.Review":                            new(api.Review),
	"api.UnifiedWebhookEventV2":             new(api.UnifiedWebhookEventV2),
	"users.UserHandlers":                    new(users.UserHandlers),
	"api.ConnectorResponse":                 new(api.ConnectorResponse),
	"api.CreateSubscriptionRequest":         new(api.CreateSubscriptionRequest),
	"api.PerformanceMetrics":                new(api.PerformanceMetrics),
	"models.Org":                            new(models.Org),
	"api.UnifiedProcessorV2Impl":            new(api.UnifiedProcessorV2Impl),
	"models.DiffHunk":                       new(models.DiffHunk),
	"auth.OrgInfo":                          new(auth.OrgInfo),
	"api.UpgradeExecuteRequest":             new(api.UpgradeExecuteRequest),
	"api.ValidateGiteaProfileRequest":       new(api.ValidateGiteaProfileRequest),
	"models.OrgWithRole":                    new(models.OrgWithRole),
	"models.UserProfile":                    new(models.UserProfile),
	"map[string]any":                        new(map[string]any),
	"api.SystemStatus":                      new(api.SystemStatus),
	"api.UnifiedReviewerChangeV2":           new(api.UnifiedReviewerChangeV2),
	"api.PasswordResponse":                  new(api.PasswordResponse),
	"api.PasswordVerifyResponse":            new(api.PasswordVerifyResponse),
	"api.ProductionURLResponse":             new(api.ProductionURLResponse),
	"api.ProductionURLRequest":              new(api.ProductionURLRequest),
	"api.SubscriptionResponse":              new(api.SubscriptionResponse),
	"payment.PurchaseConfirmationRequest":   new(payment.PurchaseConfirmationRequest),
	"api.ChunkDTO":                          new(api.ChunkDTO),
	"api.ResponseScenarioV2":                new(api.ResponseScenarioV2),
	"api.CreateAPIKeyResponse":              new(api.CreateAPIKeyResponse),
	"api.ErrorResponse":                     new(api.ErrorResponse),
	"api.ReviewEventsRepo":                  new(api.ReviewEventsRepo),
	"api.TriggerReviewRequest":              new(api.TriggerReviewRequest),
	"api.UnifiedCommitAuthorV2":             new(api.UnifiedCommitAuthorV2),
	"api.UnifiedPositionV2":                 new(api.UnifiedPositionV2),
	"api.UnifiedRepositoryV2":               new(api.UnifiedRepositoryV2),
	"users.GlobalUserWithOrg":               new(users.GlobalUserWithOrg),
	"users.OrgUserCount":                    new(users.OrgUserCount),
	"users.UserAuditEntry":                  new(users.UserAuditEntry),
	"api.CreateChunkRequest":                new(api.CreateChunkRequest),
	"api.UpdateQuantityRequest":             new(api.UpdateQuantityRequest),
}

var Enums = map[string][]any{
	"auth.ContextKey": {
		"user",
		"permission_context",
		"organization",
	},
	"auth.Permission": {
		"view_users",
		"create_users",
		"edit_users",
		"delete_users",
		"manage_roles",
		"view_org",
		"edit_org",
		"delete_org",
		"view_reviews",
		"create_reviews",
		"edit_reviews",
		"delete_reviews",
		"super_admin",
	},
	"models.CommentSeverity": {
		"info",
		"warning",
		"critical",
	},
}

var Spec = &openapi3.T{
	OpenAPI: "3.0.0",
	Info: &openapi3.Info{
		Title:   "LiveReview API",
		Version: "1.0.0",
	},
	Servers: []*openapi3.Server{
		{
			URL: "http://localhost:8888",
		},
	},
	Components: &openapi3.Components{
		Schemas:         make(openapi3.Schemas),
		SecuritySchemes: make(openapi3.SecuritySchemes),
	},
}

type GenerateOpts struct {
	Generator      *openapi3gen.Generator
	Routes         []handlers.EchoRoute
	UseTags        bool
	ApiPrefix      string
	SearchPatterns []handlers.SearchPattern
	Concurrency    int
}

func Generate(opts GenerateOpts) error {
	finder, err := handlers.NewFinder()
	if err != nil {
		return fmt.Errorf("create handlers finder: %w", err)
	}

	err = finder.Find(opts.SearchPatterns, handlers.WithConcurrency(opts.Concurrency))
	if err != nil {
		return fmt.Errorf("run finder: %w", err)
	}

	matchedHandlers := finder.Match(opts.Routes)
	for _, handler := range matchedHandlers {
		operation := openapi3.NewOperation()
		operation.Description = handler.Description()
		typed.AddPathParams(operation, handler, opts.Generator, UsedTypes)
		typed.AddQueryParams(operation, handler, opts.Generator, UsedTypes)
		typed.AddRequestBody(operation, handler, opts.Generator, Spec.Components.Schemas, UsedTypes)
		typed.AddResponses(operation, handler, opts.Generator, Spec.Components.Schemas, UsedTypes)
		typed.AddOperationId(operation, handler)
		if opts.UseTags {
			err = typed.TagOperation(operation, handler.Path(), opts.ApiPrefix)
			if err != nil {
				slog.Error("tag operation", "error", err)
				continue
			}
		}

		typed.RunHandlerHooks(Spec, operation, handler)
		Spec.AddOperation(handler.Path(), handler.Method(), operation)
	}

	return nil
}

func main() {
	const (
		apiPrefix = "/api/v1"
		useTags   = true
	)

	typed.RegisterCustomizer(typed.NewEnumsCustomizer(Enums))

	g := openapi3gen.NewGenerator(
		openapi3gen.UseAllExportedFields(),
		openapi3gen.CreateComponentSchemas(openapi3gen.ExportComponentSchemasOptions{
			ExportComponentSchemas: true,
			ExportTopLevelSchema:   true,
			ExportGenerics:         false,
		}),
		openapi3gen.SchemaCustomizer(typed.Customizer),
		openapi3gen.CreateTypeNameGenerator(typed.TypeNameGenerator),
	)

	err := typed.GenerateRefs(g, Spec.Components.Schemas, UsedTypes)
	if err != nil {
		slog.Error("generate refs for type registry", "error", err)
		os.Exit(1)
	}

	var routes []handlers.EchoRoute
	routesProvider := api.NewDocsBuilder()
	routesProvider.OnRouteAdded(func(
		host string,
		route echo.Route,
		handler echo.HandlerFunc,
		middleware []echo.MiddlewareFunc,
	) {
		routes = append(routes, handlers.EchoRoute{
			Route:       route,
			Middlewares: middleware,
		})
	})
	routesProvider.ProvideRoutes()

	opts := GenerateOpts{
		Generator: g,
		Routes:    routes,
		UseTags:   useTags,
		ApiPrefix: apiPrefix,
		SearchPatterns: []handlers.SearchPattern{
			{
				Path:      "./internal/api",
				Recursive: false,
			},
			{
				Path:      "./internal/api/handlers",
				Recursive: true,
			},
			{
				Path:      "./internal/api/auth",
				Recursive: true,
			},
			{
				Path:      "./internal/api/organizations",
				Recursive: true,
			},
			{
				Path:      "./internal/api/users",
				Recursive: true,
			},
		},
		Concurrency: 5,
	}

	err = Generate(opts)
	if err != nil {
		slog.Error("generate spec", "error", err)
		os.Exit(1)
	}

	err = typed.SaveSpec(Spec, "./docs/openapi.yaml")
	if err != nil {
		slog.Error("save spec", "error", err)
		os.Exit(1)
	}
}
