package reviewprocessor

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// CommitRef identifies a commit or commit range associated with a review.
type CommitRef struct {
	Ref  string
	Type string // "commit" | "range"
}

// InsertReviewCommits records commit refs for a review (review_commits table), so a later
// coverage lookup can match on (org_id, ref); repositoryID may be nil when unknown. Lives here
// (not internal/api) so internal/jobqueue can call it too, without an import cycle.
func InsertReviewCommits(ctx context.Context, db *sql.DB, reviewID, orgID int64, repositoryID *int64, refs []CommitRef) error {
	if len(refs) == 0 {
		return nil
	}

	valueRows := make([]string, 0, len(refs))
	args := make([]interface{}, 0, len(refs)*5)
	argN := 1
	for _, r := range refs {
		ref := strings.TrimSpace(r.Ref)
		if ref == "" {
			continue
		}
		refType := strings.TrimSpace(r.Type)
		if refType != "range" {
			refType = "commit"
		}
		valueRows = append(valueRows, fmt.Sprintf("($%d, $%d, $%d, $%d, $%d)", argN, argN+1, argN+2, argN+3, argN+4))
		args = append(args, reviewID, orgID, repositoryID, ref, refType)
		argN += 5
	}
	if len(valueRows) == 0 {
		return nil
	}

	// nosemgrep: go.lang.security.audit.database.string-formatted-query
	// Safe: valueRows contains only $N parameter placeholders generated by
	// fmt.Sprintf above (line 36), never user-supplied values. Actual values
	// are passed through db.ExecContext's args parameter.
	query := fmt.Sprintf(
		`INSERT INTO review_commits (review_id, org_id, repository_id, ref, ref_type) VALUES %s ON CONFLICT (review_id, ref) DO NOTHING`,
		strings.Join(valueRows, ", "),
	)
	_, err := db.ExecContext(ctx, query, args...)
	return err
}
