name: Validate OpenAPI YAML

on:
  pull_request:
    paths:
      - 'docs/openapi.yaml'

  push:
    paths:
      - 'docs/openapi.yaml'

jobs:
  validate-yaml:
    name: Validate YAML Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Validate YAML
        run: yamllint -d "{extends: default, rules: {line-length: disable}}" docs/openapi.yaml